### ISSUE TITLE
User-Agent not specified for Discord webhook requests

### ISSUE THREAD

**Issue by joodicator** [balinck/heavenlyhost#7]
I have not tested it, but I believe from experience of doing [something similar](https://github.com/joodicator/fto-PageBot/blob/cca181a1d11add2ec869d52ef794e1d0a5696ba7/page/dominions_discord.py#L51-L58) that the following code will fail:
https://github.com/balinck/heavenlyhost/blob/d88781fce92f9b0b005d635a2d9b9c2294e48396/heavenly/notify.py#L28-L33

Unless you provide a `User-Agent` header in the correct format according to <https://discord.com/developers/docs/reference#user-agent>, the webhook post request will be denied with a `40x` status code.

**Comment by balinck** [comment]
The lack of a User-Agent header in the payload has no effect in my testing; but in case that changes I've modified it to follow the protocol in commit 7cae34f59108da05107a51c2f023a178c87beaf2.
